/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "stm32ff.h"
#include<stdint.h>
#define FLAG 1
void delay()
{
	for(uint32_t i=0;i<50000;i++)
	{

	}
}

int main(void)
{
	GPIO_handle led1;
	led1.ptr_gp_reg= GPIOD;
	led1.pin_config_gpio.GPIO_pinumber=GPIO_PIN_NO12;
	led1.pin_config_gpio.GPIO_Pinspeed= GPIO_SPEED_MEDIUM;
	led1.pin_config_gpio.GPIO_PinPuPdControl=GPIO_NO_PULL_PUSH;
	led1.pin_config_gpio.GPIO_PinOPtype=GPIO_OP_TYPE_PP;
	led1.pin_config_gpio.GPIO_pinMode= GPIO_MODE_GPO;
	GPIO_peri_clock(GPIOD,ENABLE);
	GPIO_init(&led1);
	
	GPIO_handle button1;
	button1.ptr_gp_reg= GPIOA;
	
	button1.pin_config_gpio.GPIO_pinMode=GPIO_MODE_INP;
	button1.pin_config_gpio.GPIO_PinOPtype=GPIO_OP_TYPE_PP;
	button1.pin_config_gpio.GPIO_PinPuPdControl=GPIO_NO_PULL_PUSH;
	button1.pin_config_gpio.GPIO_Pinspeed=GPIO_SPEED_MEDIUM;
	button1.pin_config_gpio.GPIO_pinumber=GPIO_PIN_NO0;
	GPIO_peri_clock(GPIOA,ENABLE);
	GPIO_init(&button1);
	uint8_t value;
	uint8_t flag=0;
	int count=0;
	while(1)
	{
		value=GPIO_read_inp_pin(GPIOA,GPIO_PIN_NO0);
		if(value==SET)
		{  
			if(flag==1)
			{flag=0;
			count++;
			if(count%2==0)
			{
			GPIO_write_op_pin(GPIOD,GPIO_PIN_NO12,SET);
			}
			else{
				GPIO_write_op_pin(GPIOD,GPIO_PIN_NO12,RESET);
			}
			}

		}
		else{
			flag=1;
		}

	}
return 0;


}
